#playbook is a list of plays
- name: Play1
  hosts: localhost
  tasks:
    - name: play1 and task1
      ansible.builtin.debug:
      msg: "Hello from play1 and task1"


- name: Play2
  hosts: localhost
  tasks:
    - name: play2 and task2
      ansible.builtin.debug:
      msg: "Hello from play2 and task2"