- name: variable from play level
  hosts: localhost
  vars: #variable listing
    Course: "Devops"
    Trainer: "sivakumar"
    Duration: "110 hours"
  tasks:
  - name: check variables
    vars: #task level and this will be considered in o/p first then play level
      Course: "AWS and Devops"
    ansible.builtin.debug:
      msg: "Hi, i am learning {{Course}} and the trainer is {{Trainer}}, duration is {{Duration}}"