#inventory level variable
#no need to give from where to find, ansible will automatically check inventory file
- name: variable from play level
  hosts: localhost
  tasks:
  - name: check variables
    ansible.builtin.debug:
      msg: "Hi, i am learning {{Course}} and the trainer is {{Trainer}}, duration is {{Duration}}"